name: TheKamBrothers
favicon: null
layout_spectrum: 0.2233726882841438
typography_spectrum: 0.5822173757478595
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8651896773371845
  lightness: 0.7535949253942817
  saturation: 0.5148416990414262
  rhythmicContrast: 0.7269054192584008
purpose: []
